-- ============================================================================
-- FLEXR Plan Reasoning & Multi-Week Support
-- Migration: 020_plan_reasoning_fields.sql
-- Created: December 2025
-- Purpose: Add AI reasoning fields for personalized plan generation
-- ============================================================================

-- PART 1: Add plan_reasoning to training_plans
-- ============================================================================
ALTER TABLE training_plans
ADD COLUMN IF NOT EXISTS plan_reasoning JSONB,
ADD COLUMN IF NOT EXISTS athlete_context JSONB,
ADD COLUMN IF NOT EXISTS generation_model TEXT,
ADD COLUMN IF NOT EXISTS generation_timestamp TIMESTAMPTZ;

COMMENT ON COLUMN training_plans.plan_reasoning IS 'AI reasoning for phase distribution, focus areas, and progression decisions';
COMMENT ON COLUMN training_plans.athlete_context IS 'Snapshot of athlete context used for plan generation';
COMMENT ON COLUMN training_plans.generation_model IS 'AI model used for generation (e.g., grok-4-1)';
COMMENT ON COLUMN training_plans.generation_timestamp IS 'When the plan was generated by AI';

-- PART 2: Add fields to training_weeks
-- ============================================================================
ALTER TABLE training_weeks
ADD COLUMN IF NOT EXISTS is_deload BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS phase_description TEXT,
ADD COLUMN IF NOT EXISTS intensity_guidance TEXT,
ADD COLUMN IF NOT EXISTS week_reasoning TEXT;

COMMENT ON COLUMN training_weeks.is_deload IS 'Whether this is a deload/recovery week';
COMMENT ON COLUMN training_weeks.phase_description IS 'AI explanation of what this phase achieves for this athlete';
COMMENT ON COLUMN training_weeks.intensity_guidance IS 'AI guidance on intensity/effort for this week';
COMMENT ON COLUMN training_weeks.week_reasoning IS 'AI reasoning for this specific week structure';

-- PART 3: Add day_of_week to planned_workouts for better querying
-- ============================================================================
ALTER TABLE planned_workouts
ADD COLUMN IF NOT EXISTS day_of_week TEXT,
ADD COLUMN IF NOT EXISTS week_number INTEGER;

COMMENT ON COLUMN planned_workouts.day_of_week IS 'Day of week: Monday, Tuesday, etc.';
COMMENT ON COLUMN planned_workouts.week_number IS 'Week number within the training plan';

-- PART 4: Create index for multi-week queries
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_planned_workouts_week ON planned_workouts(user_id, week_number);
CREATE INDEX IF NOT EXISTS idx_training_weeks_deload ON training_weeks(is_deload) WHERE is_deload = true;

-- ============================================================================
-- Migration Complete
-- ============================================================================
